# Generated by Django 3.2.5 on 2021-08-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
