# Generated by Django 3.2.5 on 2021-08-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='numb',
            field=models.IntegerField(),
        ),
    ]
