# Generated by Django 3.2.5 on 2021-08-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210807_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='adults',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='children',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
